[patch.crates-io.orchard]
# path = "./orchard"
git = "https://github.com/hhanh00/orchard.git"
rev = "43e3d650759c395424202bb59e7b27e7786eeef3"

[workspace]
exclude = ["orchard"]
members = ["zcvlib"]
resolver = "2"

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
anyhow = "1.0"
base64 = "0.22"
bech32 = "0.11"
bincode = "2.0"
bip39 = "2.2"
blake2b_simd = "1.0"
ff = "0.13"
futures = "0.3"
halo2_proofs = "0.3"
incrementalmerkletree = "0.8"
log = "0.4"
parking_lot = "0.12"
pasta_curves = "0.5"
prost = "0.14"
rand_core = "0.6"
rocket_cors = "0.6"
reqwest = {version = "0.12", features = ["json"]}
serde_json = "1.0"
serial_test = "3.2.0"
tendermint = "0.40.1"
tendermint-abci = {version = "0.40.1", features = ["client"]}
tendermint-proto = "0.40.1"
tokio-stream = "0.1"
thiserror = "2"
tonic-prost = "0.14"
tonic-prost-build = "0.14"
zcash_address = "0.10"
zcash_note_encryption = "0.4"
zcash_protocol = "0.7"
zip32 = "0.2"

[workspace.dependencies.hex]
features = ["serde"]
version = "0.4"

[workspace.dependencies.orchard]
features = ["vote"]
version = "0.11"

[workspace.dependencies.serde]
features = ["derive"]
version = "1.0"

[workspace.dependencies.sqlx]
features = [
  "runtime-tokio",
  "sqlite",
  "macros",
  "migrate",
]
version = "0.8"

[workspace.dependencies.tokio]
features = [
  "rt-multi-thread",
  "macros",
]
version = "1.48"

[workspace.dependencies.tonic]
features = [
  "tls-ring",
  "tls-webpki-roots",
]
version = "0.14"

[workspace.dependencies.rocket]
version = "0.5"
features = [
  "json"
]
