[patch.crates-io.orchard]
path = "./orchard"
# git = "https://github.com/hhanh00/orchard.git"
# rev = "6fdb139ac117eb8854b3bfef9a89de57d54fbac5"

[workspace]
exclude = ["orchard"]
members = ["zcvlib"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
bech32 = "0.11"
bip39 = "2.2"
blake2b_simd = "1.0"
ff = "0.13"
futures = "0.3"
halo2_proofs = "0.3"
incrementalmerkletree = "0.8"
log = "0.4"
pasta_curves = "0.5"
prost = "0.14"
rand = "0.9"
rand_core = "0.9"
serde_json = "1.0"
thiserror = "2"
tracing = "0"
zcash_address = "0.10"
zcash_note_encryption = "0.4"
zcash_protocol = "0.7"

[workspace.dependencies.hex]
features = ["serde"]
version = "0.4"

[workspace.dependencies.orchard]
features = ["vote"]
version = "0.11"

[workspace.dependencies.serde]
features = ["derive"]
version = "1.0.228"

[workspace.dependencies.sqlx]
features = [
    "runtime-tokio",
    "sqlite",
    "macros",
    "migrate",
]
version = "0.8.6"

[workspace.dependencies.tokio]
features = [
    "rt-multi-thread",
    "tokio-macros",
]
version = "1.48"

[workspace.dependencies.tonic]
features = [
    "tls",
    "tls-roots",
]
version = "0.14.2"
