[default]
address = "0.0.0.0"
port = 8000

[default.limits]
bytes = "64 kB"

[default.custom]
cometrpc_port = 26657
cometbft_port = 26658
grpc_port = 9010
db_path = "vote.db"
lwd_url = "https://zec.rocks"
election = "3A1ECEBCB20EABF35941C08717ECDAE080CA3F20279BD2BD8C757E74C82F8359"
