[package]
edition = "2024"
name = "zcvlib"
version = "0.0.0"

[dependencies]
orchard = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
bip39 = { workspace = true }
bech32 = { workspace = true }
ff = { workspace = true }
hex = { workspace = true }
zcash_protocol = { workspace = true }
zcash_note_encryption = { workspace = true }
pasta_curves = { workspace = true }
zip32 = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
prost = { workspace = true }
blake2b_simd = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
