[dependencies]
orchard = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
bip39 = { workspace = true }
bech32 = { workspace = true }
ff = { workspace = true }
hex = { workspace = true }
zcash_protocol = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }

[package]
edition = "2024"
name = "zcvlib"
version = "0.1.0"
