name: Build Voter
permissions:
  contents: read

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
  workflow_call:

jobs:
  build-voter:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo npm -g install graphqurl
          NPMBIN=$(npm prefix -g)/bin
          echo "$NPMBIN" >> $GITHUB_PATH
          go install github.com/cometbft/cometbft/cmd/cometbft@v0.38
          GOBIN=$(go env GOPATH)/bin
          echo "$GOBIN" >> $GITHUB_PATH
      - name: Build
        run: |
          cargo build -r
          cometbft init --home node
          cometbft start --home node >/dev/null &
          cp zcv.toml node/
          (cd node; ../target/release/vote-cometbft  >/dev/null &)
          sleep 10
          ./target/release/voter --election-url "http://localhost:9010" &
          ./tests/voter.sh
